### ISSUE TITLE
How to include any custom module or any other python module

### ISSUE THREAD

**Issue by Biswajit2902** [GRRedWings/python3-android#11]
Hi,

Thank you for making nice setup.

I am trying to add numpy, scipy and opencv into this.

But here i saw you have kept some patch. how to make them what are those really? Are there kind of makefile?

And in source if i keep any official link that should work fine or not.

Can you please help me in this.

Thank you.

**Comment by GRRedWings** [comment]
Sorry for the late reply, this got lost in the bottom of my inbox.

The short answer  is that the patch files are really a fancy diff.  They
are needed when cross compiling for Android requires a code change. We make
the changes we need to make, generate the patch file. then the make applies
the patches after it downloads the source file.

So if you want to include more libraries, I would recommend adding them 1
at a time.  You will notice a mk folder in the root.  Add say numpy/x.x.x
(where x.x.x is the version you are building).  Follow the pattern.
readline/7.0 has no changes, so that is a good place to start.

Once you make those changes, you will need to make sure that your library
is called in the make.  edit the Makefile in the root.  See line 48 and
make similar edits for numpy.

B
